apiVersion: apps/v1
kind: Deployment
metadata:
  name: commenting-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commenting
  template:
    metadata:
      labels:
        app: commenting
    spec:
      containers:
        - name: commenting
          image: grmek/commenting:1.0.0-SNAPSHOT-DEV
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: commenting
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: commenting
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: commenting
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: commenting-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
status:
  currentReplicas: 1
  desiredReplicas: 1
  currentCPUUtilizationPercentage: 0
