apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-viewer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd-viewer
  template:
    metadata:
      labels:
        app: etcd-viewer
    spec:
      containers:
        - name: etcd-viewer
          image: nikfoundas/etcd-viewer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: etcd-viewer
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: etcd-viewer
