apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-managing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-managing
  template:
    metadata:
      labels:
        app: image-managing
    spec:
      containers:
        - name: image-managing
          image: grmek/image-managing:1.0.0-SNAPSHOT-4.1
          env:
            - name: KUMULUZEE_DISCOVERY_CLUSTER
              value: gcloud
            - name: KUMULUZEE_SERVER_BASEURL
              value: http://35.239.231.140:8080
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: image-managing
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: image-managing
