apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-processing
  template:
    metadata:
      labels:
        app: image-processing
    spec:
      containers:
        - name: image-processing
          image: grmek/image-processing:1.0.0-SNAPSHOT-DEV
          imagePullPolicy: Always
          env:
            - name: KUMULUZEE_STREAMING_KAFKA_PRODUCER_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: sasl-jaas-config
                  key: sasl-jaas-config
            - name: KUMULUZEE_STREAMING_KAFKA_CONSUMER_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: sasl-jaas-config
                  key: sasl-jaas-config
          ports:
            - containerPort: 8083
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: image-processing
spec:
  type: ClusterIP
  ports:
    - port: 8083
      protocol: TCP
      targetPort: server
  selector:
    app: image-processing
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: image-processing
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: image-processing-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
status:
  currentReplicas: 1
  desiredReplicas: 1
  currentCPUUtilizationPercentage: 0
