apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharing
  template:
    metadata:
      labels:
        app: sharing
    spec:
      containers:
        - name: sharing
          image: grmek/sharing:1.0.0-SNAPSHOT-DEV
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: sharing
spec:
  type: ClusterIP
  ports:
    - port: 8082
      protocol: TCP
      targetPort: server
  selector:
    app: sharing
